### ISSUE TITLE
Fix transition between pages

### ISSUE THREAD

**Issue by djmtype** [tylergaw/mpa-view-transitions-sandbox#2]
I think the spec was updated since the last commit? Otherwise, the demos don't seem to work as expected.

To make them work, in shared.css, add:  

```css
@view-transition {
    navigation: auto;
}
```

Tested with Chrome Canary 131, Brave 1.70, Safari Tech Preview 18.0
